// questions.c
#include "questions.h"

Question questions[MAX_QUESTIONS] = 
{ 
    {"Quel est le plus grand océan du monde ?", {" Océan Atlantique", "  Océan Pacifique", "  Océan Indien", "  Océan Arctique"}},
    {"Qui a peint La Joconde ?", {" Leonardo da Vinci", "  Michel-Ange", "  Pablo Picasso", "  Vincent van Gogh"}},
    {"Quel est le plus long fleuve du monde ?", {" Le Nil", "  L'Amazone", "  Le Mississippi", "  Le Yangtsé"}},
    {"Qui a écrit Le Petit Prince ?", {" Antoine de Saint-Exupéry", "  Victor Hugo", "  Gustave Flaubert", "  Albert Camus"}},
    {"Quelle est la capitale du Canada ?", {" Ottawa", "  Toronto", "  Vancouver", "  Montréal"}},
    {"Quelle est la planète la plus proche du soleil ?", {" Mercure", "  Vénus", "  Terre", "  Mars"}},
    {"Qui a découvert la pénicilline ?", {" Alexander Fleming", "  Louis Pasteur", "  Marie Curie", "  Albert Einstein"}},
    {"Quel est l'élément le plus abondant dans l'atmosphère terrestre ?", {" Azote", "  Oxygène", "  Dioxyde de carbone", "  Hydrogène"}},
    {"Qui a écrit Les Misérables ?", {" Victor Hugo", "  Alexandre Dumas", "  Emile Zola", "  Honoré de Balzac"}},
    {"Quel est le plus haut sommet du monde ?", {" Everest", "  K2", "  Kangchenjunga", "  Lhotse"}},
    {"Qui a réalisé le film Forrest Gump ?", {" Robert Zemeckis", "  Steven Spielberg", "  Quentin Tarantino", "  Martin Scorsese"}},
    {"Dans quel film Leonardo DiCaprio n'a-t-il pas remporté l'Oscar du meilleur acteur ?", {" The Revenant", "  Titanic", "  The Wolf of Wall Street", "  Inception"}},
    {"Quel film a remporté l'Oscar du meilleur film en 2020 ?", {" Parasite", "  1917", "  Joker", "  Nomadland"}},
    {"Qui a joué le rôle de Batman dans The Dark Knight ?", {" Christian Bale", "  Ben Affleck", "  Michael Keaton", "  George Clooney"}},
    {"Quel est le premier film de la trilogie Le Seigneur des Anneaux ?", {" La Communauté de l'Anneau", "  Les Deux Tours", "  Le Retour du Roi", "  La Bataille des Cinq Armées"}},
    {"Qui a réalisé le film Inception ?", {" Christopher Nolan", "  David Fincher", "  Ridley Scott", "  James Cameron"}},
    {"Quelle actrice a remporté l'Oscar de la meilleure actrice pour son rôle dans La La Land ?", {" Emma Stone", "  Meryl Streep", "  Jennifer Lawrence", "  Cate Blanchett"}},
    {"Quel film a remporté le premier Oscar du meilleur film d'animation ?", {" Shrek", "  Toy Story", "  Le Roi Lion", "  Shrek 2"}},
    {"Qui a réalisé le film Pulp Fiction ?", {" Quentin Tarantino", "  Martin Scorsese", "  Francis Ford Coppola", "  Steven Spielberg"}},
    {"Quel acteur a joué le rôle principal dans Le Parrain ?", {" Marlon Brando", "  Al Pacino", "  Robert De Niro", "  James Caan"}},
    {"Qui a été le premier empereur de France ?", {" Napoléon Bonaparte", "  Louis XIV", "  Charlemagne", "  Louis Napoléon Bonaparte"}},
    {"Où a eu lieu la bataille de Waterloo ?", {" Belgique", "  France", "  Allemagne", "  Pays-Bas"}},
    {"Qui a écrit L'Art de la guerre ?", {" Sun Tzu", "  Julius Caesar", "  Alexandre le Grand", "  Hannibal"}},
    {"Quel événement a marqué le début de la Révolution française ?", {" Prise de la Bastille", "  L'Exécution de Louis XVI", "  La Déclaration des droits de l'homme et du citoyen", "  La Fuite à Varennes"}},
    {"Qui était le premier président des États-Unis ?", {" George Washington", "  Thomas Jefferson", "  John Adams", "  Abraham Lincoln"}},
    {"Où a eu lieu la première guerre mondiale ?", {" Europe", "  Asie", "  Amérique du Nord", "  Afrique"}},
    {"Qui a été le dernier empereur de Russie ?", {" Nicolas II", "  Alexandre II", "  Pierre le Grand", "  Ivan le Terrible"}},
    {"Quel événement a marqué la fin de la Seconde Guerre mondiale en Europe ?", {" La capitulation de l'Allemagne", "  La bataille de Stalingrad", "  Le débarquement en Normandie", "  La conférence de Yalta"}},
    {"Quel empereur romain a incendié Rome ?", {" Néron", "  Caligula", "  Auguste", "  Trajan"}},
    {"Qui a dirigé la Révolution cubaine et est devenu Premier ministre de Cuba en 1959 ?", {" Fidel Castro", "  Che Guevara", "  Fulgencio Batista", "  Raul Castro"}},
    {"Quel est le plus grand pays du monde en termes de superficie ?", {" Russie", "  Canada", "  Chine", "  États-Unis"}},
    {"Quelle est la capitale de l'Australie ?", {" Canberra", "  Sydney", "  Melbourne", "  Brisbane"}},
    {"Sur quel continent se trouve le Sahara ?", {" Afrique", "  Asie", "  Amérique", "  Europe"}},
    {"Quel est le plus long fleuve d'Amérique du Sud ?", {" Amazone", "  Paraná", "  Orénoque", "  Rio de la Plata"}},
    {"Quel est le point le plus bas de la Terre ?", {" Mer Morte", "  Vallée de la Mort", "  Fosse des Mariannes", "  Lac Baïkal"}},
    {"Quel est le plus grand lac d'Afrique ?", {" Lac Victoria", "  Lac Tanganyika", "  Lac Malawi", "  Lac Turkana"}},
    {"Quel est le plus haut sommet d'Afrique ?", {" Kilimandjaro", "  Mont Kenya", "  Mont Stanley", "  Mont Ruwenzori"}},
    {"Quelle est la plus grande île du monde ?", {" Groenland", "  Madagascar", "  Borneo", "  Sumatra"}},
    {"Quelle est la capitale de l'Inde ?", {" New Delhi", "  Bombay", "  Bangalore", "  Calcutta"}},
    {"Quelle est la capitale de l'Argentine ?", {" Buenos Aires", "  Rio de Janeiro", "  Santiago", "  Montevideo"}},
    {"Quel est le langage de programmation utilisé pour créer des pages web ?", {" HTML", "  Python", "  Java", "  C++"}},
    {"Quel est le composant principal d'un ordinateur qui exécute les instructions des programmes ?", {" Processeur (CPU)", "  Carte graphique (GPU)", "  Mémoire vive (RAM)", "  Disque dur (HDD/SSD)"}},
    {"Quel est le système d'exploitation développé par Apple pour ses ordinateurs personnels ?", {" macOS", "  Windows", "  Linux", "  Android"}},
    {"Quel terme désigne un logiciel malveillant conçu pour causer des dommages à un ordinateur ou à un réseau ?", {" Virus", "  Antivirus", "  Pare-feu", "  Navigateur"}},
    {"Quel protocole est utilisé pour envoyer et recevoir des courriers électroniques sur Internet ?", {" SMTP", "  HTTP", "  FTP", "  DHCP"}},
    {"Quel est le navigateur web développé par Google ?", {" Google Chrome", "  Mozilla Firefox", "  Safari", "  Microsoft Edge"}},
    {"Quel est le langage de programmation souvent utilisé pour créer des applications Android ?", {" Java", "  C#", "  Swift", "  Python"}},
    {"Quel type de fichier contient un ensemble d'instructions exécutables par un ordinateur ?", {" Fichier exécutable", "  Fichier texte", "  Fichier image", "  Fichier compressé"}},
    {"Quel est le périphérique d'entrée principal utilisé pour saisir du texte sur un ordinateur ?", {" Clavier", "  Souris", "  Stylet", "  Microphone"}},
    {"Quel est le langage de balisage utilisé pour structurer le contenu des pages web ?", {" HTML", "  CSS", "  JavaScript", "  PHP"}},
    {"Quelle nation a envoyé le premier homme dans l'espace ?", {" Union soviétique", "  États-Unis", "  Chine", "  France"}},
    {"Quel était le nom du premier homme à voyager dans l'espace ?", {" Youri Gagarine", "  Neil Armstrong", "  John Glenn", "  Buzz Aldrin"}},
    {"Quel était le nom du premier satellite artificiel lancé dans l'espace ?", {" Spoutnik 1", "  Explorer 1", "  Vanguard 1", "  Luna 1"}},
    {"Quelle mission a posé le premier homme sur la Lune ?", {" Apollo 11", "  Apollo 13", "  Apollo 8", "  Apollo 17"}},
    {"Qui était le premier homme à marcher sur la Lune ?", {" Neil Armstrong", "  Buzz Aldrin", "  Alan Shepard", "  Michael Collins"}},
    {"Quelle station spatiale est actuellement en orbite autour de la Terre ?", {" Station spatiale internationale (ISS)", "  Mir", "  Skylab", "  Tiangong"}},
    {"Quel est le nom de la première femme à voyager dans l'espace ?", {" Valentina Terechkova", "  Sally Ride", "  Mae Jemison", "  Peggy Whitson"}},
    {"Quel était le nom du premier animal à être envoyé dans l'espace ?", {" Laïka", "  Ham", "  Albert II", "  Felicette"}},
    {"Quelle agence spatiale a lancé le rover Perseverance sur Mars en 2021 ?", {" NASA", "  ESA (Agence spatiale européenne)", "  Roscosmos (Agence spatiale russe)", "  CNSA (Administration spatiale nationale chinoise)"}},
    {"Quel est le nom du premier vaisseau spatial à avoir transporté un homme dans l'espace ?", {" Vostok 1", "  Mercury-Redstone 3 (Freedom 7)", "  Gemini 3", "  Voskhod 1"}},
    {"Quel domaine de l'informatique se concentre sur la création de machines intelligentes capables de simuler des processus cognitifs humains ?", {" Intelligence artificielle (IA)", "  Réalité virtuelle (VR)", "  Cybersécurité", "  Réseaux neuronaux"}},
    {"Quel est le terme utilisé pour désigner un programme informatique capable d'apprendre à partir des données sans être explicitement programmé ?", {" Apprentissage automatique (Machine Learning)", "  Algorithme", "  Robotique", "  Intelligence artificielle générale (AGI)"}},
    {"Quel est l'algorithme d'apprentissage automatique largement utilisé pour la classification et la régression ?", {" Réseaux de neurones", "  SVM (Support Vector Machine)", "  K-means", "  Naive Bayes"}},
    {"Quel terme désigne la capacité d'un système d'IA à comprendre, interpréter et répondre au langage humain de manière naturelle ?", {" Traitement du langage naturel (NLP)", "  Vision par ordinateur", "  Robotique", "  Simulation de la pensée humaine"}},
    {"Quel est le domaine de l'IA qui se concentre sur la création de systèmes informatiques capables de voir et d'interpréter le monde visuel de la manière dont les humains le font ?", {" Vision par ordinateur", "  Traitement automatique des données", "  Réseaux de neurones", "  Algorithmes génétiques"}},
    {"Quel est le terme utilisé pour décrire la capacité d'un système d'IA à prendre des décisions et à agir de manière autonome sans intervention humaine ?", {" Autonomie", "  Intelligence artificielle forte (ASI)", "  Agent intelligent", "  Auto-apprentissage"}},
    {"Quelle méthode d'apprentissage automatique utilise des réseaux de neurones artificiels pour imiter le fonctionnement du cerveau humain ?", {" Apprentissage profond (Deep Learning)", "  Apprentissage supervisé", "  Apprentissage non supervisé", "  Apprentissage par renforcement"}},
    {"Quel est le domaine de l'IA qui se concentre sur la création de robots et de systèmes capables d'effectuer des tâches physiques de manière autonome ?", {" Robotique", "  Vision par ordinateur", "  Traitement automatique des données", "  Apprentissage automatique"}},
    {"Quel est le terme utilisé pour désigner la capacité d'un système d'IA à améliorer ses performances au fil du temps grâce à l'expérience et à la rétroaction ?", {" Apprentissage par renforcement", "  Apprentissage supervisé", "  Apprentissage non supervisé", "  Auto-apprentissage"}},
    {"Quel roman a pour personnage principal Jean Valjean ?", {" Les Misérables", "  Madame Bovary", "  L'Étranger", "  Le Rouge et le Noir"}},
    {"Qui est l'auteur de Romeo et Juliette ?", {" William Shakespeare", "  Jane Austen", "  Charles Dickens", "  Fiodor Dostoïevski"}},
    {"Quel est le titre du premier livre de la saga Harry Potter ?", {" Harry Potter à l'école des sorciers", "  Harry Potter et la Chambre des secrets", "  Harry Potter et le Prisonnier d'Azkaban", "  Harry Potter et la Coupe de feu"}},
    {"Qui est l'auteur de L'Étranger ?", {" Albert Camus", "  Marcel Proust", "  Gustave Flaubert", "  Jean-Paul Sartre"}},
    {"Quel est le nom du héros du roman Don Quichotte ?", {" Don Quichotte", "  Sancho Panza", "  Don Juan", "  Don Diego"}},
    {"Qui a écrit Orgueil et Préjugés ?", {" Jane Austen", "  Emily Brontë", "  Charlotte Brontë", "  Louisa May Alcott"}},
    {"Quel est le titre du célèbre poème de Charles Baudelaire ?", {" Les Fleurs du mal", "  Le Spleen de Paris", "  Les Misérables", "  Le Rouge et le Noir"}},
    {"Qui est l'auteur de 1984 ?", {" George Orwell", "  Aldous Huxley", "  Ray Bradbury", "  Arthur C. Clarke"}},
    {"Quel écrivain est connu pour ses aventures de Sherlock Holmes ?", {" Arthur Conan Doyle", "  Agatha Christie", "  Edgar Allan Poe", "  Sir Arthur Ignatius Conan Doyle"}}
};
